### ISSUE TITLE
I'm not able to compile

### ISSUE THREAD

**Issue by ru-sh** [hashmismatch/freertos.rs#1]
Hello. I just started new project and added freertos_rs as a dependecy.
When I try to compile I get following message:

cargo.exe test --no-run --message-format=json

   Compiling freertos_rs v0.1.0

{"reason":"compiler-message","package_id":"freertos_rs 0.1.0 (registry+https://github.com/rust-lang/crates.io-index)","target":{"kind":["lib"],"name":"freertos_rs","src_path":"\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\freertos_rs-0.1.0\\src\\lib.rs"},"message":{"children":[],"code":{"code":"E0554","explanation":null},"level":"error","message":"#[feature] may not be used on the stable release channel","rendered":null,"spans":[{"byte_end":1787,"byte_start":1769,"column_end":19,"column_start":1,"expansion":null,"file_name":"\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\freertos_rs-0.1.0\\src\\lib.rs","is_primary":true,"label":null,"line_end":56,"line_start":56,"suggested_replacement":null,"text":[{"highlight_end":19,"highlight_start":1,"text":"#![feature(alloc)]"}]}]}}

{"reason":"compiler-message","package_id":"freertos_rs 0.1.0 (registry+https://github.com/rust-lang/crates.io-index)","target":{"kind":["lib"],"name":"freertos_rs","src_path":"\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\freertos_rs-0.1.0\\src\\lib.rs"},"message":{"children":[],"code":{"code":"E0554","explanation":null},"level":"error","message":"#[feature] may not be used on the stable release channel","rendered":null,"spans":[{"byte_end":1812,"byte_start":1788,"column_end":25,"column_start":1,"expansion":null,"file_name":"\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\freertos_rs-0.1.0\\src\\lib.rs","is_primary":true,"label":null,"line_end":57,"line_start":57,"suggested_replacement":null,"text":[{"highlight_end":25,"highlight_start":1,"text":"#![feature(collections)]"}]}]}}

{"reason":"compiler-message","package_id":"freertos_rs 0.1.0 (registry+https://github.com/rust-lang/crates.io-index)","target":{"kind":["lib"],"name":"freertos_rs","src_path":"\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\freertos_rs-0.1.0\\src\\lib.rs"},"message":{"children":[],"code":{"code":"E0554","explanation":null},"level":"error","message":"#[feature] may not be used on the stable release channel","rendered":null,"spans":[{"byte_end":1831,"byte_start":1813,"column_end":19,"column_start":1,"expansion":null,"file_name":"\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\freertos_rs-0.1.0\\src\\lib.rs","is_primary":true,"label":null,"line_end":58,"line_start":58,"suggested_replacement":null,"text":[{"highlight_end":19,"highlight_start":1,"text":"#![feature(fnbox)]"}]}]}}

{"reason":"compiler-message","package_id":"freertos_rs 0.1.0 (registry+https://github.com/rust-lang/crates.io-index)","target":{"kind":["lib"],"name":"freertos_rs","src_path":"\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\freertos_rs-0.1.0\\src\\lib.rs"},"message":{"children":[],"code":null,"level":"error","message":"aborting due to 3 previous errors","rendered":null,"spans":[]}}

error: Could not compile `freertos_rs`.

**Comment by rudib** [comment]
Nightly Rust is a requirement, you are on the stable compiler. You'll also probably need something like Xargo to cross compile to your target MCU architecture.
