### ISSUE TITLE
freertos_rs_delete_semaphore takes UBaseType_t in C wrapper

### ISSUE THREAD

**Issue by uzytkownik** [hashmismatch/freertos.rs#15]
A small type detected by compiling with warnings
```
// from shim.rs
extern {
	// ...
	pub fn freertos_rs_queue_delete(queue: FreeRtosQueueHandle);
	// ...
```

And in C code:

```
// queue.c
void vQueueDelete( QueueHandle_t xQueue )
// shim.c
void freertos_rs_queue_delete(UBaseType_t queue)
```
There are also a few minor problems:

- `uint8_t` is used and passed as `char *` when transforming string (strict aliasing violation) (`freertos_rs_spawn_task` and `freertos_rs_timer_create`)
 - `freertos_rs_queue_send_isr` have unused variable `ret`. 

I can send a pull request for them later today but they should be easy enough to fix

**Comment by rudib** [comment]
Should be fixed in the latest version of the shim, thanks for the report. I'll also probably modify the test environment to compile with -Wall to be really strict on such issues.
